---
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image
on:
  # push:
  #   branches:
  #   - dev-v2.0.0
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registries:
    uses: khanlab/actions/.github/workflows/workflow-release_task-deployDocker.yml@no-latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
