---
# This workflow will trigger wet run testing before a PR is merged with the master branch

name: Wet run test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install non-python dependencies
      run: |
        sudo apt-get install -y graphviz-dev unzip wget

      - name: Setup Python environment
        uses: khanlab/actions/.github/actions/action-setup_task-installPyProject@v0.3.2
        with:
          python-version: 3.9
          install-library: true

      - name: Setup env for hippunfold
        run: |
          echo "DENS='--output_density 0p5mm 1mm 2mm unfoldiso'" >> $GITHUB_ENV
          echo "RUNOPTS='--use-singularity --cores all -p'" >> $GITHUB_ENV
      
      - name: Download folder from URL
        run: |
          wget "https://files.ca-1.osf.io/v1/resources/k2nme/providers/osfstorage/66759a948dfe890189cb7178/?zip=" -O lowresMRI.zip

      - name: Unzip downloaded folder
        run: |
          unzip lowresMRI.zip -d lowresMRI
      
      - name: Generate sub_volumes.tsv
        run: |
          poetry run hippunfold lowresMRI test-lowresMRI participant --participant_label 01 --modality T1w $DENS $RUNOPTS

      - name: Compare sub_volumes.tsv with the baseline configuration
        run: |
          diff test_data/lowresMRI/sub-01/anat/sub-01_space-cropT1w_desc-subfields_atlas-multihist7_volumes.tsv test-lowresMRI/hippunfold/sub-01/anat/sub-01_space-cropT1w_desc-subfields_atlas-multihist7_volumes.tsv
