---
# This workflow will trigger wet run testing before a PR is merged with the master branch

name: Wet run test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install non-python dependencies
        run: |
          sudo apt-get install -y graphviz-dev

      - name: Setup Python environment
        uses: khanlab/actions/.github/actions/action-setup_task-installPyProject@v0.3.2
        with:
          python-version: 3.9
          install-library: true

      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3 
      
      - name: Generate sub_volumes.tsv
        run: |
          poetry run hippunfold test_data/lowresMRI test-lowresMRI participant --participant-label 01 --modality T1w --output_density 0p5mm 1mm 2mm unfoldiso --until get_subfield_vols_subj --use-singularity --cores all -p

      - name: Compare sub_volumes.tsv
        run: |
          diff test_result/lowresMRI/sub-01/anat/sub-01_space-cropT1w_desc-subfields_atlas-multihist7_volumes.tsv test-lowresMRI/hippunfold/sub-01/anat/sub-01_space-cropT1w_desc-subfields_atlas-multihist7_volumes.tsv
